language: ruby
rvm:
  - 1.8.7
script: 'puppet parser validate `find . {manifests} -name "*.pp"`'
script: 'puppet-lint --with-filename manifests'
script: 'rake spec'
env:
  - PUPPET_VERSION="2.7"
branches:
  only:
    - possible_enhancements
